name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-2022

    defaults:
    run:
      shell: pwsh

    env:
      Project: "GW Launcher\GW Launcher.csproj"
      PublishProfile: "FrameworkDependent"

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    - name: Restore Tools
      run: dotnet tool restore

    - name: GitVersion
      run: dotnet dotnet-gitversion /output buildserver

    - name: Publish GW Launcher
      run: msbuild $Env:Project /target:Restore;Publish /property:PublishProfile=$Env:PublishProfile;Version=$Env:GitVersion_FullSemVer

    # Upload the MSIX package: https://github.com/marketplace/actions/upload-a-build-artifact
    # - name: Upload build artifacts
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: MSIX Package
    #     path: ${{ env.Wap_Project_Directory }}\AppPackages